Resolves #81: Vision
Baret/pltcmd pull request #121
Opened 2020-10-31 10:29 UTC by Loomie

2020-11-06 20:36 UTC, Baret requested changes

2020-11-06 20:36 UTC, Baret commented on game/engine/src/main/kotlin/de/gleex/pltcmd/game/engine/systems/behaviours/LookAround.kt
> +    private fun lookAround(from: Coordinate, world: WorldMap): CoordinateArea {
I could write a lenthy comment about what I think of this implementation and what might be done differently, but I guess it's easiest when we talk about it in discord real quick :)

2020-11-08 12:34 UTC, Loomie commented on game/engine/src/main/kotlin/de/gleex/pltcmd/game/engine/systems/behaviours/LookAround.kt
> +    private fun lookAround(from: Coordinate, world: WorldMap): CoordinateArea {
Reworked with Commit 15e7f0cdfd7396c4809068b4a6582b3e033d04a2

2020-12-27 10:41 UTC, Baret reviewed
Just some small things. After that we can go to master.

Maybe I can fix those myself, but when you @Loomie get to it first, go ahead :)

2020-12-27 10:41 UTC, Baret commented on model/world/src/main/kotlin/de/gleex/pltcmd/model/world/coordinate/CoordinateRectangle.kt
> +        CoordinateArea({ (bottomLeftCoordinate..topRightCoordinate).toSortedSet() }) {
Don't we have the constructor with `Coordinate.Progression` for this?

2020-12-27 10:41 UTC, Baret commented on model/world/src/main/kotlin/de/gleex/pltcmd/model/world/coordinate/MainCoordinate.kt
> +    override fun compareTo(other: MainCoordinate): Int {
This is currently copy&pasted from `Coordinate`. Can we create a generic comparator taking a northing and easting?

2020-12-28 07:24 UTC, Loomie commented on model/world/src/main/kotlin/de/gleex/pltcmd/model/world/coordinate/CoordinateRectangle.kt
> +        CoordinateArea({ (bottomLeftCoordinate..topRightCoordinate).toSortedSet() }) {
But this constructor is lazy! I should have removed the other one...

2020-12-28 07:50 UTC, Loomie commented on game/ui/src/main/kotlin/de/gleex/pltcmd/game/ui/renderers/SignalVisualizer.kt
> +                .launchIn(CoroutineScope(Dispatchers.Default))
The default dispatcher uses different threads (confirmed with a `println`). I think the problem is the sequential nature of the flow. A buffer didn't help either.

2020-12-28 09:43 UTC, Baret approved these changes
Master, here we come!

2020-12-28 09:47 UTC, merged