Trying to use improved signaling for vision
Baret/pltcmd pull request #122
Opened 2020-11-19 19:55 UTC by Baret

Instead of writing a new line of sight algorithm to use it for vision I tried abstracting the radio signal code. In the end it is just a line of sight algo itself so why not reuse it? And we might later reuse it again for sound or maybe even more.

2020-11-21 10:52 UTC, Loomie requested changes
Not bad, but needs some polishing.

2020-11-21 10:52 UTC, Loomie commented on model/signals/core/src/main/kotlin/de/gleex/pltcmd/model/signals/core/SignalPower.kt
> +abstract class SignalPower(val power: Double) {
Not a data class? I'm not sure if this should be abstract. The `initialProcessingValue` (which is a function and not a field?) can also be implemented directly in `Signal` where it is used. There the "processing" is specific. Also I think the function should be named something like `createFullStrength()` or `getMaxSignalPower()`. OK a radio may not transmit on full power, so maybe call it `emitSignal()` there to indicate that a new signal is created at the origin.

2020-11-21 10:52 UTC, Loomie commented on model/signals/core/src/main/kotlin/de/gleex/pltcmd/model/signals/core/SignalStrength.kt
> +data class SignalStrength(
Please use this new project also in `radio` to not duplicate all the classes. Currently the review is a bit hard to distinguish between moved, copied and new code.

2020-11-21 10:52 UTC, Loomie commented on model/signals/pom.xml
> +            </dependency>
Add a separator comment like the on ein `model/pom.xml` to end the `modules` section:
```
<!-- other internal projects -->
```

2020-11-21 10:52 UTC, Loomie commented on model/signals/signals-all/pom.xml
> +            <artifactId>core</artifactId>
This dependency is also transient from `vision`. So I think this is not needed in the aggregator. Only the root projects of signal dependencies are required here.

2020-11-21 10:52 UTC, Loomie commented on model/signals/vision/src/main/kotlin/de/gleex/pltcmd/model/signals/vision/Vision.kt
> +        return value - 0.3
Is this final or is a `TODO` missing that depends on the terrain type?

2020-11-21 10:52 UTC, Loomie commented on model/signals/vision/src/main/kotlin/de/gleex/pltcmd/model/signals/vision/Vision.kt
> +            SignalStrength(max(calculationValue, SignalStrength.MIN_ALLOWED_VALUE))
Why is this not directly in the `SignalStrength` constructor? The field for the minimum value is also contained there. So this function wants to be in SignalStrength where it is just the constructor. Then this function can also be removed from `PropagationModel`.

2020-11-21 10:52 UTC, Loomie commented on model/signals/vision/src/main/kotlin/de/gleex/pltcmd/model/signals/vision/VisionPower.kt
> +    override fun initialProcessingValue(): Double = 1.0
The KDoc says "range in tiles" but it is a value between 0.0 and 1.0? So where it is mapped to more than one tile? As `SignalPower` just wraps a `Double` I don't know if we need special sub types. The minium and maxium allowed values are provided by the PropagationModel anyways.

2020-11-21 10:52 UTC, Loomie commented on model/signals/vision/src/main/kotlin/de/gleex/pltcmd/model/signals/vision/VisualSignal.kt
> +        override val model: Vision
OK, I asked myself when viewing at `Signal` already: Why are two values abstract and two are fields of `Signal`. Now I see that there is no difference at all. I think all fields should be kept in the super class where they are defined already.

Also: Why is `Signal` abstract? This class adds no functionality. Just provide the values to the constructor.

2020-11-21 10:52 UTC, Loomie commented on model/world/src/main/kotlin/de/gleex/pltcmd/model/world/Sector.kt
> +class Sector(val origin: Coordinate, tiles: SortedSet<WorldTile>) : Comparable<Sector>, WorldArea(tiles) {
When removing `data` add all the generated functions like `equals/hashCode`!

2020-11-21 10:52 UTC, Loomie commented on model/world/src/main/kotlin/de/gleex/pltcmd/model/world/WorldArea.kt
> + * A part of the [WorldMap] containing a set of [WorldTile]s. As world tiles map a terrain to a coordiante, a world
```suggestion
 * A part of the [WorldMap] containing a set of [WorldTile]s. As world tiles map a terrain to a coordinate, a world
```

2020-11-21 10:52 UTC, Loomie commented on model/world/src/main/kotlin/de/gleex/pltcmd/model/world/WorldMap.kt
> +                .toSortedSet())
Maybe the other way around is more performant; Instead of filtering the whole world just map the area to its WorldTiles. The sector.origin optimization may be enough or even better to optimize the performance. We will see...

2020-11-21 10:52 UTC, Loomie commented on model/world/src/main/kotlin/de/gleex/pltcmd/model/world/coordinate/CoordinateArea.kt
> +    protected val mainCoordinatesMap: Map<MainCoordinate, SortedSet<Coordinate>> =
The values are never used (currently). Also `mainCoordinates` and `sectorOrigins` do the same. I think sector origins should be used as they are more fine grained and so the purpose of filtering is more effective.

2020-11-24 20:14 UTC, Baret commented on game/engine/src/main/kotlin/de/gleex/pltcmd/game/engine/entities/EntitySet.kt
> +            allEntities.removeAll(entities.toList())
It is a `PersistentSet`, all modifications return a new set. So here a new set is being created and then "wrapped up" into an `EntitySet`.

2020-11-24 20:14 UTC, Baret commented on game/engine/src/main/kotlin/de/gleex/pltcmd/game/engine/entities/EntitySet.kt
> +}
You might be right. I got closer and closer to "this is simply a set" while coding it ^^

2020-11-24 20:18 UTC, Baret commented on game/pom.xml
> +                <type>pom</type>
It does not contain any code, it is simply a shortcut for "core, vision, radio and possibly more", so that you only need one dependency instead of 2 or 3 or later even more. I was not sure how to create such an "aggregator module" (it is the wrong term in maven speak).

2020-11-24 20:21 UTC, Baret commented on model/signals/core/src/main/kotlin/de/gleex/pltcmd/model/signals/core/PropagationModel.kt
> +interface PropagationModel<P: SignalPower> {
I had a conceptual problem here. I wanted to have the initial `SignalPower` in the model so it can be used as reference in `throughTerrain´ and other calls. It would be turned into a `SignalStrength` immediately and the method calls would return a reduced `SignalStrength`. But somehow that didn't work out for how I wanted to implement vision so I made it like this:

In the beginning there is a `SignalPower`, then it is turned into some arbitrary `Double` to calculat the signal loss along the way, and then this double is turned into a remaining `SignalStrength`. But I gotta think about that again...

2020-11-24 20:37 UTC, Baret commented on game/engine/src/main/kotlin/de/gleex/pltcmd/game/engine/systems/facets/Detects.kt
> +object Detects: BaseFacet<GameContext>(
Coming soon (tm) ;P

2020-11-24 20:40 UTC, Baret commented on model/signals/vision/src/main/kotlin/de/gleex/pltcmd/model/signals/vision/Vision.kt
> +        return value - 0.3
Nope, that was just some quick "Gotta put some numbers here". Details to follow.

2020-11-24 20:45 UTC, Baret commented on model/world/src/main/kotlin/de/gleex/pltcmd/model/world/WorldMap.kt
> +                .toSortedSet())
I want to write a little performance test and run it with those optimizations and without (on the master branch).

2020-11-25 09:24 UTC, Baret commented on game/engine/src/main/kotlin/de/gleex/pltcmd/game/engine/GameContext.kt
> +        return Maybe.ofNullable(entities.allElements().find { it.currentPosition == location })
We should simply move both methods to `EntitySet`. Which increases its value ;)

2020-11-25 10:05 UTC, Baret commented on game/engine/src/main/kotlin/de/gleex/pltcmd/game/engine/entities/EntitySet.kt
> +    private var allEntities: PersistentSet<GameEntity<T>> = initialSet.toPersistentSet()
I can not reassign the `PersistentSet` when I use it a delegate. But as it is immutable (mutating operations return a new instance) it needs to be a `var`. 
And yes, it needs to be a `PersistentSet` as I already ran into a `ConcurrentModificationException` when playing around with it (it was a simple `Set` before).

2020-11-25 10:43 UTC, Baret commented on game/engine/src/main/kotlin/de/gleex/pltcmd/game/engine/entities/EntitySet.kt
> +}
After some improvement and additions I think we should keep it. There would be _so_ many extension functions that it makes sense for me to couple them together in an own class. As it extends `Set` you can use the default methods on it anyways.
And I would like to add performance logging later which is also best when we have some kind of `performanceLogger` field in the class.

2020-11-25 10:58 UTC, Baret commented on game/engine/src/test/kotlin/de/gleex/pltcmd/game/engine/systems/behaviours/LookAroundTest.kt
> +/*
Yup, Unittests are still a TODO.

2020-11-27 13:12 UTC, Baret commented on model/signals/core/src/main/kotlin/de/gleex/pltcmd/model/signals/core/Signal.kt
> +//    }
Nope, use it ;)

2020-12-05 13:06 UTC, Loomie commented on game/engine/src/main/kotlin/de/gleex/pltcmd/game/engine/entities/EntitySet.kt
> +    fun firstElementAt(location: Coordinate): Maybe<GameEntity<ElementType>> =
We have a typealias for `GameEntity<ElementType>` it is named `ElementEntity` ;)

2020-12-05 13:16 UTC, Loomie commented on game/engine/src/main/kotlin/de/gleex/pltcmd/game/engine/entities/types/Seeing.kt
> +var SeeingEntity.vision: Vision
As it is a `var` it is not only visble but also editable!

2020-12-05 13:33 UTC, Loomie commented on game/ui/src/main/kotlin/de/gleex/pltcmd/game/ui/renderers/SignalVisualizer.kt
> +        lastDrawnMap = signalMap
Why not directly remember the blocks? The values of the map are never used.

2020-12-05 13:40 UTC, Loomie commented on model/communication/pom.xml
> +    <artifactId>communication</artifactId>
The packes have not been changed. It is not consistent with the other projects where the package reassembles the project hierarchy:
* Folder: <pltcmd>/model/communication
* Package: ...pltcmd.model.radio

Maybe we can switch the package names of `communication` and `radio`:
`de.gleex.pltcmd.model.radio.communication`
gets
`de.gleex.pltcmd.model.communication.radio`

2020-12-05 13:58 UTC, Loomie commented on model/signals/core/src/main/kotlin/de/gleex/pltcmd/model/signals/core/SignalPropagator.kt
> +     * Called for each tile a signals travels through the given [TerrainType].
```suggestion
     * Called for each tile a signal travels through the given [TerrainType].
```

2020-12-05 14:04 UTC, Loomie commented on model/signals/radio/src/main/kotlin/de/gleex/pltcmd/model/signals/radio/RadioSignalPropagator.kt
> +        fun maxRangeInTiles(power: Double): Int {
Put the function below the fields/constants.

2020-12-05 14:18 UTC, Loomie commented on model/signals/vision/src/main/kotlin/de/gleex/pltcmd/model/signals/vision/VisionPropagator.kt
> +            log.trace("\t\tSignal travels through air")
```suggestion
            log.trace("\t\Vision travels through air")
```

2020-12-05 14:25 UTC, Loomie commented on model/signals/vision/src/main/kotlin/de/gleex/pltcmd/model/signals/vision/builder/WorldMapExtension.kt
> +    return Signal(
```suggestion
    return Vision(
```

2020-12-05 14:27 UTC, Loomie commented on model/signals/vision/src/main/kotlin/de/gleex/pltcmd/model/signals/vision/builder/WorldMapExtension.kt
> +            areaOf(CoordinateCircle(location, radius)),
I think we need a `circleAt()` besides `areaOf()` in `WorldMap`.

2020-12-05 14:33 UTC, Loomie commented on model/signals/vision/src/main/kotlin/de/gleex/pltcmd/model/signals/vision/builder/WorldMapExtension.kt
> +            areaOf(CoordinateCircle(location, radius)),
Done in 63f252f

2020-12-06 10:09 UTC, Baret commented on model/communication/pom.xml
> +    <artifactId>communication</artifactId>
There will be no `radio` package in the `communication` module as it is being moved over to the new `signals.radio` module. But I only started with that.

If you like go ahead and delete the old package and fix up the compile errors :D

2020-12-06 21:16 UTC, Baret commented
Thanks for the review! I will now go on to move the radio stuff over to the new signals module and delete the old stuff. After that I gotta move/fix/write some tests and then this PR is actually ready to be reviewed and merged back into your branch ;)
This just started as "little experiment"... oh well...

2020-12-08 09:34 UTC, Baret commented on model/communication/pom.xml
> +    <artifactId>communication</artifactId>
Done.

2020-12-21 10:27 UTC, Loomie requested changes
Found "something" :D

2020-12-21 10:27 UTC, Loomie commented on model/communication/src/test/kotlin/de/gleex/pltcmd/model/radio/RadioSenderTest.kt
> +/*
TODO implement or move tests

2020-12-21 10:27 UTC, Loomie commented on model/communication/src/test/kotlin/de/gleex/pltcmd/model/radio/broadcasting/RadioSignalTest.kt
> +//class RadioSignalTest: WordSpec() {
TODO update tests

2020-12-21 10:27 UTC, Loomie commented on model/communication/src/test/kotlin/de/gleex/pltcmd/model/radio/broadcasting/SignalStrengthTest.kt
> +//class SignalStrengthTest : WordSpec({
TODO update tests

2020-12-21 10:27 UTC, Loomie commented on model/communication/src/test/kotlin/de/gleex/pltcmd/model/radio/testhelpers/Matchers.kt
> +//infix fun SignalStrength.shouldBeExactly(expected: Double) = this.strength shouldBeExactly expected
Remove?

2020-12-21 10:27 UTC, Loomie commented on model/world/src/main/kotlin/de/gleex/pltcmd/model/world/Sector.kt
> +class Sector(val origin: Coordinate, tiles: SortedSet<WorldTile>) : Comparable<Sector>, WorldArea(tiles) {
This is not resolved!

2020-12-21 10:27 UTC, Loomie commented on model/world/src/main/kotlin/de/gleex/pltcmd/model/world/coordinate/CoordinateArea.kt
> +    protected val mainCoordinatesMap: Map<MainCoordinate, SortedSet<Coordinate>> =
>  This conversation was marked as resolved by Baret 

Why? -> Reopen.

2020-12-21 10:34 UTC, Baret commented on model/world/src/main/kotlin/de/gleex/pltcmd/model/world/WorldMap.kt
> +                .toSortedSet())
Opened #127 for this.

2020-12-21 10:56 UTC, Baret commented on model/world/src/main/kotlin/de/gleex/pltcmd/model/world/Sector.kt
> +class Sector(val origin: Coordinate, tiles: SortedSet<WorldTile>) : Comparable<Sector>, WorldArea(tiles) {
Oops :)
done in 724bd81

2020-12-21 11:01 UTC, Baret commented on model/world/src/main/kotlin/de/gleex/pltcmd/model/world/coordinate/CoordinateArea.kt
> +    protected val mainCoordinatesMap: Map<MainCoordinate, SortedSet<Coordinate>> =
I think I wanted to provide future subclasses a way of more efficiently get coordinates. But yes, YAGNI.

Done in 55beba3

2020-12-22 13:37 UTC, Baret commented on game/engine/src/main/kotlin/de/gleex/pltcmd/game/engine/Game.kt
> +            (entity as ElementEntity).callsign.toString()
ElemenEntity has a `name` field? Or what do you mean?

2020-12-23 13:02 UTC, Baret commented on game/engine/src/main/kotlin/de/gleex/pltcmd/game/engine/Game.kt
> +        val radioSender = RadioSender(elementPosition, RadioPower(2000.0), world)
The idea of presets is great! I added some in 90e3aba but they are not yet in use.

2020-12-23 13:08 UTC, Baret commented on game/engine/src/main/kotlin/de/gleex/pltcmd/game/engine/Game.kt
> +            (entity as ElementEntity).callsign.toString()
Ah, the interface `Entity` has a field `name` documented with:
> Shorthand for accessing EntityType.name.

But as we only use typealiases for the entitytypes, we can not directly override `val name`. So in this case it makes more sense to get the callsign for a meaningful log message than to simply use `entity.name` as it would simply return "element" for every `ElementEntity`.

2020-12-23 13:31 UTC, Baret commented on game/engine/src/main/kotlin/de/gleex/pltcmd/game/engine/entities/EntitySet.kt
> +    fun without(vararg entities: GameEntity<T>): EntitySet<T> =
I tried that but stumbled upon a typing problem. To have the code like your snippet you would need to define `without` outside of the class. So it is independent of an actual entity set. But then you do not know the type of entities which means you would need to define it as
```kotlin
fun without(vararg entities: AnyGameEntity): (AnyGameEntity) -> Boolean {
// ...
}
```

This means you could provide entites of any type which may have no effect at all. While in the current implementation you can only filter out entites that have the same type as the ones contained in the set.
And I like the chaining style it currently has, although I see your point that we create new collections over and over again while doing so.

2020-12-23 13:36 UTC, Baret commented on game/engine/src/main/kotlin/de/gleex/pltcmd/game/engine/entities/EntitySet.kt
> +            Maybe.ofNullable(allElements().firstOrNull { it.currentPosition == location })
Great! 👍

2020-12-23 14:07 UTC, Baret commented on game/engine/src/main/kotlin/de/gleex/pltcmd/game/engine/entities/EntitySet.kt
> +            Maybe.ofNullable(allElements().firstOrNull { it.currentPosition == location })
And as I found out, `Sequence` is what you want to use when laziliy filtering large collections. And as the "root entity set" in `Game` contains _all_ entities I guess it will become pretty large at some point.

2020-12-23 21:18 UTC, Baret commented on game/ui/src/main/kotlin/de/gleex/pltcmd/game/ui/fragments/tileinformation/SignalVisualizationFragment.kt
> +                    it as CommunicatingEntity
Because it is not nessecary in kotlin :P

2020-12-25 14:26 UTC, Baret commented
I hope I got all your comments fixed. Maybe something got lost on the way because I did not resolve your comments as I guess that is your job now in the re-review.

I kept the tests out because most of this stuff is only well testable with #129. 

It is astonishing how much simpler the `RadioSender` and `BroadcastEvent` stuff became now that basically everything except the `Transmission` is contained in the signal :)

2020-12-25 19:26 UTC, merged