Contact reports, resolves #130
Baret/pltcmd pull request #131
Opened 2020-12-28 14:32 UTC by Loomie

The Detects facet has a threshold on which the full entity or only a generic entity is visble. Corresponding commands are handled by the new ReportContacts facet which starts a conversation with the HQ.

2020-12-29 22:18 UTC, Baret requested changes
This is a solid first throw. As I wrote the issue description I wondered how to track a contact. I mean how you would know that the element you see now in location B is the one you saw one tick earlier in location A. But simply saving the whole entity is easy and clever. What information the contact containing this entity yields is something different. My first thought was to have a data class with a bunch of nullable fields that get populated depending on how well visible the contact is. We can still have this. But it should also contain the "last updated" tickID and the actual entity so you can reveal more and more of it.

Another thing is that this first approach does not aim at the target structure. I like your distinction of detecting elements and unknown. And of course currently all that will happen is that a contact report is being sent. But at some point there will be some decision making. And that is the point where we can distinguish `Facets` from "modular AI"-style `Goal`s. When adding something like "ok, depending on my current rules of engagement, I react this or that way to that new contact" we could cram that logic into the `Detects` or `ReportContacts` facet. But hey, facets should be "dumb", they should execute their designated commands without questioning. Ok, alternatively we put it into new facets and commands. But then we also need to make sure they all get built into the entity in the `EntityFactory` (in the correct order, btw). So IMO this is a good point to see that something should be put into `Goal`s.

With them we have the advantage of building tiny AI-blocks that consist of other goals. And in the end they only send rather simple and direct commands like nerves to the muscels. When we get to the point of thinking "oh, we need some decision making here" it should be the point of considering using goals.

Of course they should be moved into an own module as they will become quite numerous (I guess). And to offer a clean API. There might be public goals being directly used by the `ExecuteOrder` facet and others. Other goals might be internal because they are sub-goals.
This step does not necessarily need to be done in this PR though.

2020-12-29 22:18 UTC, Baret commented on game/engine/src/main/kotlin/de/gleex/pltcmd/game/engine/systems/facets/ReportContacts.kt
> +        // TODO where does the receiver call sign come from? Is it the fixed superior element (of the faction #62)? Remembered from last conversation?
I just realized: This also clogs up the element's conversation queue (in the current implementation). When an element detects another one multiple ticks in a row it triggers 4 tick long conversations which pile up in the queue.

2020-12-30 09:00 UTC, Loomie commented on game/engine/src/main/kotlin/de/gleex/pltcmd/game/engine/systems/facets/Detects.kt
> +            runBlocking {
Yes, I wanted to run the commands asynchronously beside iterating the entities. But you are right, it may be too complicated as every command must be run anyways.

2020-12-30 09:22 UTC, Loomie commented on game/engine/src/main/kotlin/de/gleex/pltcmd/game/engine/systems/facets/Detects.kt
> +                "${(seeing as ElementEntity).callsign.name.padEnd(25)} sees $seenText at ${
You are right, it is function and not a value. So it prints "sees () -> kotlin.String at"

2020-12-30 09:40 UTC, Loomie commented on game/engine/src/main/kotlin/de/gleex/pltcmd/game/engine/systems/facets/ReportContacts.kt
> +        if (isNew(reporter as SeeingEntity, toReport)) {
you mean _infix_ but yeah, I changed it.

2020-12-30 09:44 UTC, Loomie commented on game/engine/src/main/kotlin/de/gleex/pltcmd/game/engine/systems/facets/ReportContacts.kt
> +            // TODO should be put in a separate facet that is run at the end after all others got the new contacts
We already have that in Detects. So there a Contact-Command should only be fired when new? But that would not be enough for engaging enemies on each turn. Maybe the DetectedCommand should contain all that information:
- isNew?
- how visible?

Because currently the two different `DetectedElement` and `DetectedUnknown` are already cumbersome.

2020-12-30 09:50 UTC, Loomie commented on game/engine/src/main/kotlin/de/gleex/pltcmd/game/engine/systems/facets/ReportContacts.kt
> +        // TODO where does the receiver call sign come from? Is it the fixed superior element (of the faction #62)? Remembered from last conversation?
Currently a receiver must know that a transmission is for him. So we need to rework the communications model for this. I would not start such an overhaul in this issue. So I want to keep an addressee.

> it triggers 4 tick long conversations

I tried to remove the `establishComms` from the conversation, but we don't allow that 😢 
```
Exception in thread "DefaultDispatcher-worker-3" java.lang.IllegalArgumentException: No opening transmission has been set for conversation between Alpha and HQ. Either set it directly or use init()
	at de.gleex.pltcmd.model.radio.communication.building.ConversationBuilder.build(ConversationBuilder.kt:27)
[...]
```

2020-12-30 09:53 UTC, Loomie commented on game/engine/src/main/kotlin/de/gleex/pltcmd/game/engine/systems/facets/ReportContacts.kt
> +        // TODO where does the receiver call sign come from? Is it the fixed superior element (of the faction #62)? Remembered from last conversation?
> but we don't allow that 

OK, now I correctly use the ConversationBuilder.

2020-12-30 10:18 UTC, Loomie commented on game/engine/src/main/kotlin/de/gleex/pltcmd/game/engine/systems/facets/Detects.kt
> +            runBlocking {
After changing the code I remember why I did this: `executeCommand()` is a suspension function!
> Suspension functions can be called only within coroutine body

So we need a `runBlocking` or must not use `responseWhenCommandIs()` (as its parameter is not `suspend`ed). But the `Channel` is still an optimization that is optional. I will remove it and use the `map` as it is more clear what is done here.

2020-12-30 12:29 UTC, Loomie commented on game/engine/src/main/kotlin/de/gleex/pltcmd/game/engine/systems/facets/ReportContacts.kt
> +        reporter.sendCommand(reportCommand)
Now I directly use `startConversation()`. Mostly because `sendCommand` is a suspension function that needs a coroutine :p

2020-12-30 12:32 UTC, Loomie commented
I restructured `Detects` now it just checks if something is really visible and forwards that knowledge to anyone that wants to use it (send a command). The `ReportContacts` facet now does the plausiblity checks what needs to be reported over the radio and what not: Only enemy elements and unknown entities are reported. Also only "new" contacts are reported. A contact is new, if it was not already visible in the previous update. That is now a Tick thing that is not on the real timeline (entities that hop in that time between different states are not captured).

2020-12-30 21:45 UTC, Baret commented on game/engine/src/main/kotlin/de/gleex/pltcmd/game/engine/systems/facets/ReportContacts.kt
> +        // TODO where does the receiver call sign come from? Is it the fixed superior element (of the faction #62)? Remembered from last conversation?
Isn't the "learn stuff from transmission" in the "is not for me" branch of the radio receiver?
I thought it would instantly work by just parsing "Contact.*" from messages there. But I will take a look...

2021-01-01 12:41 UTC, Baret commented
Without having reviewed yet: there are test failures ;)
See `FightingTest`

2021-01-02 08:58 UTC, Loomie commented
Another contact report is done if an unknown contact becomes hostile. For that the visibility of the previous contact is compared to the current. If the vision is better now another report is send to the HQ.

2021-01-02 21:40 UTC, Baret commented on game/engine/src/main/kotlin/de/gleex/pltcmd/game/engine/systems/facets/ReportContacts.kt
> +        reporter.sendCommand(reportCommand)
The subtle difference is that `startConversation()` queues the conversation for _next tick_. And also bypasses the systems/messages stuff.
`commandersIntent.butNow(RadioGoal(conversation))` is not suspending ;)
But I am not exactly sure if it makes the entity start the conversation this tick. It _should_ though...

2021-01-03 14:38 UTC, Baret commented on game/engine/src/main/kotlin/de/gleex/pltcmd/game/engine/messages/DetectedEntity.kt
> +    val previousVisibility: Visibility,
The documentation sounds like this parameter might have a default value.

2021-01-03 14:38 UTC, Baret commented on game/engine/src/main/kotlin/de/gleex/pltcmd/game/engine/systems/facets/ReportContacts.kt
> +    override suspend fun receive(detected: DetectedEntity): Response {
A warning here says:
> The corresponding parameter in the supertype 'BaseFacet' is named 'message'. This may cause problems when calling this function with named arguments.

As the systems are called by the engine/the entities (aka the library) this might acutally become a problem. So better use the overridden name.

2021-01-03 14:38 UTC, Baret commented on game/engine/src/main/kotlin/de/gleex/pltcmd/game/engine/systems/facets/ReportContacts.kt
> + * Sends a contact report to the hq when something is detected.
Still: A contact report should be broadcast to all friendlies so everyone can take note of it. 

BTW it is acutlly even easier to implement it in `ReceivingCommunicator#gatherInformationFrom` becaue it is only called when a message is not directed at the receiver. This means, when you send this message to HQ we have to use the "write down and remember a contact" logic twice.

2021-01-03 14:38 UTC, Baret commented on game/engine/src/main/kotlin/de/gleex/pltcmd/game/engine/systems/facets/ReportContacts.kt
> +    fun reportContact(reporter: CommunicatingEntity, toReport: PositionableEntity, context: GameContext): Response {
All these funs can be private.

2021-01-03 14:38 UTC, Baret commented on model/signals/core/src/main/kotlin/de/gleex/pltcmd/model/signals/core/SignalStrength.kt
> +        private val strength: Double): Comparable<SignalStrength> {
👍

2021-01-03 14:38 UTC, Baret commented on model/signals/core/src/main/kotlin/de/gleex/pltcmd/model/signals/core/SignalStrength.kt
>      override fun compareTo(other: SignalStrength): Int = strength.compareTo(other.strength)
We could reuse `compareTo(other: Double)` here.

2021-01-10 11:01 UTC, Loomie commented on game/engine/src/main/kotlin/de/gleex/pltcmd/game/engine/entities/types/Seeing.kt
> +internal fun SeeingEntity.visibleEntities(): EntitySet<Positionable> = contacts.getAll().keys.toEntitySet()
> but the element still remembers that "contact".

So it is part of #104 "knowledge".

2021-01-10 11:06 UTC, Loomie commented on game/engine/src/main/kotlin/de/gleex/pltcmd/game/engine/entities/types/Seeing.kt
> +internal fun SeeingEntity.visibleEntities(): EntitySet<Positionable> = contacts.getAll().keys.toEntitySet()
> we need a different word
I think a "hot contact" is actually a contact: The element is in contact with that element. The knowledge can only be "remembered contacts" or "seen elements".

2021-01-10 11:17 UTC, Loomie commented on game/engine/src/main/kotlin/de/gleex/pltcmd/game/engine/extensions/EntityExtensions.kt
> +        else        -> type.name + System.identityHashCode(this)
Because I also add the object hash. So I get: `type + number` which says in the log: It is a entity of type X with identity Y. If `this.name` would return a unique name it would not be necessary. And using `this.name` but actually wanting `type.name` hides the intention and may change if the implementation of `this.name` changes.

2021-01-10 11:22 UTC, Loomie commented on game/engine/src/main/kotlin/de/gleex/pltcmd/game/engine/systems/facets/ReportContacts.kt
> + * Sends a contact report to the hq when something is detected.
Every radio call is broadcasted ;) That is why we have the `gatherInformationFrom()` part when receiving transmissions. But the conversation must have an addressee. So we might introduce a broadcast type for conversations, but keep it simple ;)

2021-01-10 11:34 UTC, Loomie commented on game/engine/src/main/kotlin/de/gleex/pltcmd/game/engine/systems/facets/ReportContacts.kt
> +    fun reportContact(reporter: CommunicatingEntity, toReport: PositionableEntity, context: GameContext): Response {
And they can be public so they can be called on a model level instead of the technical level that needs an Amethys command. So for me it should be in an own model class instead of a private method :D Actually we could separate the entity logic and context/response parts. But it is hard to decide how overengineered this needs to be. Do we need a ServiceProviderFactory that gives us a ResponseCommandFactory which we can use? And has that factory a pluggable set of ReportVisisbleEntityDeciders? So we could go all the extensible and responsibility parts. But for me the `public` is enough reusability ;) Software engineering is hard!

2021-01-10 11:50 UTC, Loomie commented on game/engine/src/main/kotlin/de/gleex/pltcmd/game/engine/systems/facets/ReportContacts.kt
> +        // TODO where does the receiver call sign come from? Is it the fixed superior element (of the faction #62)? Remembered from last conversation?
See [discussion in Discord](https://discord.com/channels/688347805735321747/688353038074904676/797793549755088917)

2021-01-23 13:10 UTC, Baret reviewed
Almost finished :)
I think we just need to merge master one more time and that's it.

2021-01-23 13:10 UTC, Baret commented on game/options/src/main/kotlin/de/gleex/pltcmd/game/options/GameOptions.kt
> +    val commandersCallSign = "HQ"
We have `GameConstants` for that. I don't think this callsign is something the player might be able to change later. I imagine [factions](#62) to have a name which may be set by the player. But the commander of a faction always reports in as "HQ" (for now).

2021-01-23 22:35 UTC, Baret approved these changes
Had to fix an exception and a little merge fail ;)

But now it looks good for a first throw for #130 
Let's go to `master` with that.

2021-01-23 22:36 UTC, merged